mh_test/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mhsite/', include("mhsite.urls")),
    url(r'^', include("mhsite.urls")),
]

mhsite/urls.py
from django.conf.urls import url
from mhsite import views
from django.contrib.auth.views import login, password_reset, password_reset_done, password_reset_confirm, \
    password_reset_complete

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^accounts/login/$', views.loginf, name='log'),
    url(r'^accounts/logout/$', views.logoutf, name='log'),
    url(r'^accounts/register/$', views.registration, name='register'),
    url(r'^accounts/pwdreset/$', views.pwdreset, name='mess'),
    url(r'^accounts/reset-password/$', password_reset, {'template_name': 'mhsite/accounts/forget.html'}, name='login'),
    url(r'^accounts/reset-password/done/$', password_reset_done, {'template_name': 'mhsite/accounts/forgetview.html'},
        name='password_reset_done'),
    url(r'^accounts/reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)$', password_reset_confirm,
        {'template_name': 'mhsite/accounts/forgetupdate.html'}, name='password_reset_confirm'),
    url(r'^accounts/reset-password/complete/$', password_reset_complete, {'template_name': 'mhsite/accounts/forgetview2.html'},
        name='password_reset_complete'),
    url(r'^students/application/$', views.application, name='application'),
    url(r'^admins/manage/$', views.allocation, name='alloc'),
    url(r'^admins/allocation/$', views.allocation, name='alloc'),
    url(r'^gallery/$', views.gallery, name='gallery'),
    url(r'^contacts/$', views.contacts, name='contacts'),
    url(r'^mess/$', views.mess, name='mess'),
    url(r'^students/studentscorner/$', views.students, name='students'),
    url(r'^expense_list/$', views.expense_list, name='expense_list'),
    url(r'^expense_tracker/(?P<year>[0-9]{4})-(?P<month>[0-9]{2})-(?P<day>[0-9]{2})/$', views.expense, name='expense'),
    url(r'^expense/$', views.expense_list, name='expense_list'),
    url(r'^expense/add$', views.Report.as_view(), name='report'),
    url(r'^expense/(?P<year>[0-9]{4})-(?P<month>[0-9]{2})-(?P<day>[0-9]{2})/$', views.ReportDetails.as_view(),
        name='report_details'),
    url(r'^mess_cut/$', views.mess_cut, name='mess_cut'),
    url(r'^mess_cut/apply/$', views.mess_cut_apply, name='mess_cut_apply'),
    url(r'^mess/secretary/processing/$', views.processing, name='mess_cut_processing'),
    url(r'^mess/secretary/processing/(?P<mess_id>[0-9]+)/$', views.approval, name='mess_cut_approval'),
    url(r'^mess/secretary/processing/(?P<mess_id>[0-9]+)/submit$', views.final, name='mess_cut_final'),
    url(
        r'^mess/secretary/processing/(?P<type>(approved|rejected))/(?P<mess_id>[0-9]+)/(?P<year>[0-9]+)/(?P<month>([A-Z][a-z]+))/$',
        views.edit, name='mess_cut_edit'),
    url(
        r'^mess/secretary/processing/(?P<type>(approved|rejected))/(?P<mess_id>[0-9]+)/(?P<year>[0-9]+)/(?P<month>([A-Z][a-z]+))/submit$',
        views.submit_edit, name='mess_cut_edit_submit'),
]

mhsite/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.core.validators import RegexValidator
from django.contrib.auth.models import User
from django.db import models
import calendar

# Create your models here.
class Application(models.Model):
    admission_number=models.CharField(max_length=7,
                                    validators=[RegexValidator(regex=r'^[0-9]{4}/[0-9]{2}$',message='The format for admission number is 1234/17')],
                                    help_text='1234/17',unique=True)
    first_name=models.CharField(max_length=100)
    last_name=models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    room_number = models.CharField(max_length=4)
    address=models.CharField(max_length=500)
    pincode=models.CharField(max_length=6,validators=[RegexValidator(regex=r'^[0-9]{6}$',message='Enter a valid pincode')])
    phone=models.CharField(max_length=10,validators=[RegexValidator(regex=r'[0-9]{10}',message='Invalid mobile number')])
    date_of_birth=models.DateField()
    category=models.CharField(max_length=10)

    def __str__(self):
        return self.first_name+" "+self.last_name

class Profile(models.Model):
    admission_number =  models.CharField(max_length=7, default='1234/17')
    fname = models.CharField(max_length=100, default='Name')
    lname = models.CharField(max_length=100, default='Last_Name')
    email = models.EmailField()
    room_number = models.IntegerField(default=0)
    phone = models.CharField(max_length=10,validators=[RegexValidator(regex=r'[0-9]{10}',message='Invalid mobile number')])

    def __str__(self):
        return self.fname+' '+self.lname


class Expense(models.Model):
    #MONTH_CHOICES=[(str(i), calendar.month_name[i]) for i in range(1,13)]

    #month=models.CharField(max_length=9, choices=MONTH_CHOICES, default='1')
    date=models.DateField(unique=True)
    item1=models.DecimalField(default=0.0,decimal_places=2,max_digits=10, verbose_name="Supplyco")
    item2=models.DecimalField(default=0.0,decimal_places=2,max_digits=10, verbose_name="Gas")
    item3=models.DecimalField(default=0.0,decimal_places=2,max_digits=10, verbose_name="Meat")
    item4=models.DecimalField(default=0.0,decimal_places=2,max_digits=10, verbose_name="Fish")
    item5=models.DecimalField(default=0.0,decimal_places=2,max_digits=10, verbose_name="Others")

    @property
    def total(self):
        "Return the total expense"
        sum=0
        sum+=(self.item1+self.item2+self.item3+self.item4+self.item5)
        return sum
    total_expense=property(total)

    def __str__(self):
        return str(self.date)

class MessCut(models.Model):
    email=models.EmailField(unique=True)
    mess_cut_dates = models.CharField(max_length=100000)
    approved_dates = models.CharField(max_length=100000, default='{}')
    rejected_dates = models.CharField(max_length=100000, default='{}')
    applied_date = models.CharField(max_length=100000, null = True)
    process_date = models.CharField(max_length=100000, null = True)
    def __str__(self):
        return self.email

mhsite/views.py
from __future__ import unicode_literals
from django.shortcuts import render, redirect, get_object_or_404
from mhsite.forms import RegistrationForm, ApplicationForm, ExpenseForm, ReportForm, MessCutForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from mhsite.models import Application, Expense, MessCut, Profile
from django.views import View
from django.views.generic.edit import FormView
from django.db import IntegrityError
from django.utils.dateformat import format
from datetime import date, timedelta, datetime
import json, os, calendar
from django.http import HttpResponse


def studentlist():
    pwd = os.path.dirname(__file__)
    file = open(pwd + '/students.csv')
    data = file.readlines()
    file.close()
    students = []
    for row in data:
        a = row.split(',')
        a[3] = a[3].replace('\n', '')
        students.append(a)
    students.pop(0)
    return students


def home(request):
    return render(request, 'mhsite/index.html')


def gallery(request):
    return render(request, 'mhsite/gallery.html')


def mess(request):
    if request.user.is_authenticated:
        return redirect('/mess_cut')
    else:
        return render(request, 'mhsite/messlogout.html')


def allocation(request):
    if request.user.is_authenticated and (request.user.username == 'admin' or request.user.username == 'secretary'):
        if request.method == 'POST':
            students = studentlist()
            Profile.objects.filter().delete()
            for x in students:
                p = Profile(admission_number=x[0], fname=x[1], lname=x[2], email=x[3])
                p.save()

            return redirect('/')

        else:
            students = studentlist()
            args = {'data': students}
            return render(request, 'mhsite/admin/allocation.html', args)
    else:
        return redirect('/')


def registration(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            if Profile.objects.filter(admission_number=form.cleaned_data.get('admission_number')).exists():
                if User.objects.filter(username=form.cleaned_data.get('email')).exists():
                    args = {'error': 'User already exist', 'erlink': '/accounts/register'}
                    return render(request, 'mhsite/regerror.html', args)
                else:
                    form.save()
                    return redirect('/accounts/login')

            else:
                args = {'error': 'You are not selected', 'erlink': '/accounts/register'}
                return render(request, 'mhsite/regerror.html', args)
        else:
            args = {'forms': form}
            return render(request, 'mhsite/accounts/registration.html', args)

    else:
        form = RegistrationForm()
        args = {'forms': form}
        return render(request, 'mhsite/accounts/registration.html', args)


def loginf(request):
    form = AuthenticationForm
    args = {'form': form}
    if request.method == 'POST':
        username = request.POST['username'].strip()
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)

                return redirect('/')
        else:
            args = {'error': 'Login Failed', 'erlink': '/accounts/login'}
            return render(request, 'mhsite/regerror.html', args)

    return render(request, 'mhsite/accounts/login.html', args)


def logoutf(request):
    logout(request)
    return render(request, 'mhsite/accounts/logout.html')


def pwdreset(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = PasswordChangeForm(data=request.POST, user=request.user)
            if form.is_valid():
                form.save()
                return redirect('/accounts/login')
            else:
                args = {'error': 'Password reset failed', 'erlink': '/accounts/pwdreset'}
                return render(request, 'mhsite/regerror.html', args)

        else:
            form = PasswordChangeForm(user=request.user)
            args = {'form': form}
            return render(request, 'mhsite/accounts/passwordreset.html', args)
    else:
        return redirect('/')


def application(request):
    if request.user.is_authenticated:
        form = ApplicationForm()
        args = {'form': form}
        if request.method == 'POST':
            form = ApplicationForm(request.POST)
            if Application.objects.filter(email=request.user.username).exists():
                instance = Application.objects.get(email=request.user.email)
                form = ApplicationForm(request.POST,instance = instance)

            if form.is_valid():

                form.save()

                return redirect('/students/studentscorner')
            else:

                form = ApplicationForm(request.POST)

                students = studentlist()
                usern = request.user.username
                users = ''
                for x in students:
                    if x[3] == usern:
                        users = x
                args = {'form': form, 'usern': users}
                return render(request, 'mhsite/students/application.html', args)
        else:
            students = studentlist()
            usern = request.user.username
            users = ''
            for x in students:
                if x[3] == usern:
                    users = x

            if Application.objects.filter(email=request.user.username).exists():
                instance = Application.objects.get(email=request.user.email)
                form = ApplicationForm(instance = instance)

            if users is not None:

                args = {'form': form, 'usern': users, }
                return render(request, 'mhsite/students/application.html', args)
    else:
        return redirect('/')

def contacts(request):
    return render(request, 'mhsite/contacts.html')


def students(request):
    if request.user.is_authenticated:

        if Application.objects.filter(email=request.user.username).exists():
            details = Application.objects.get(email=request.user.username)
            args = {'data': details}
            return render(request, 'mhsite/students/studentscorner.html', args)

        else:
            return redirect('/students/application')
    else:
        return application(request)


def mess_cut(request, year=str(datetime.now().year), month=str(datetime.now().month)):
    try:
        email = request.user.email
        mess = MessCut.objects.get(email=email)
        if request.method == 'POST':
            year = str(request.POST['year'])
            month = str(datetime.strptime(request.POST['month'], '%B').month)


        approved_dates = json.loads(mess.approved_dates)
        rejected_dates = json.loads(mess.rejected_dates)

        if year in approved_dates:
            if month in approved_dates[year]:
                approved_dates = approved_dates[year][month]

        if year in rejected_dates:
            if month in rejected_dates[year]:
                rejected_dates = rejected_dates[year][month]

        processing_dates = json.loads(mess.mess_cut_dates)['processing']

        years = [year for year in json.loads(mess.approved_dates)]
        dupe = [year for year in json.loads(mess.rejected_dates) if year not in years]
        if len(dupe) > 0:
            for year in dupe:
                years.append(year)

        if len(years) == 0:
            years = [year]
        cal = {'months': list(calendar.month_name), 'years': years,
               'default': [year, datetime.strftime(datetime(2017, int(month), 1), '%B')]}
        args = {'calendar': cal, 'processing': processing_dates, 'approved': approved_dates, 'rejected': rejected_dates,
                'dtype': [isinstance(approved_dates, dict), isinstance(rejected_dates, dict)]}

        return render(request, 'mhsite/mess/mess_user.html', args)

    except AttributeError:
        return redirect('/accounts/login')

    except:
        if request.method == 'POST':
            error = True
            month = request.POST['month']
        else:

            error = False
            month = datetime.strftime(datetime(2017, int(month), 1), '%B')
        if not Application.objects.filter(email=request.user.username).exists():
            return redirect('/students/application')
        cal = {'months': list(calendar.month_name), 'years': [year], 'default': [year, month]}
        args = {'calendar': cal, 'status': error}
        return render(request, 'mhsite/mess/mess_user.html', args)


def date_gen(lst, start_date, end_date, objects=None):
    delta = end_date - start_date

    for i in range(delta.days + 1):
        lst['processing'].append(str(start_date + timedelta(days=i)))
    seen = set()
    seen_add = seen.add
    lst['processing'] = [x for x in lst['processing'] if not (x in seen or seen_add(x))]

    return lst


def duplicate(date_list, date_type):
    duplicate_dates = []
    for date in date_list['processing']:
        date_obj = datetime.strptime(date, '%Y-%m-%d')
        year = str(date_obj.year)
        month = str(date_obj.month)
        if year in date_type:

            if month in date_type[year]:

                if date in date_type[str(date_obj.year)][str(date_obj.month)]:
                    duplicate_dates.append(date)

                else:
                    continue

            else:
                continue

        else:
            continue
    return duplicate_dates


def mess_cut_apply(request):
    if request.method == 'POST':
        form = MessCutForm(request.POST)

        if form.is_valid():
            email = request.user.email
            start_date = form.cleaned_data['start_date']

mhsite/templates/mhsite/students/application.html
{% extends 'base.html' %}

{% block body %}

    <div class='container'>
        <div class="card card-panel" style="margin-top:15px; background-color:rgba(0, 0, 0, 0.6)">
            <h3 style="text-align:center;color:rgba(255,255,255,0.87); ">Application Form</h3>

            <form method="post" class='col s12'>
            {% csrf_token %}


              <div class='row'>
                  <div class='input-field col s8 offset-s2'>
                      <input type="text" value='{{usern.0}}' name="admission_number" id="id_admission_number" required maxlength="7" />
                      <label for="id_admission_number">Admission number:</label>
                      
                  </div>
              </div>





              <div class='row'>
                  <div class='input-field col s8 offset-s2'>
                      <input type="text" value='{{usern.1}}' name="first_name" id="id_first_name" required maxlength="100" />
                      <label for="id_first_name">First name:</label>
                      <div class="error">
                        {{form.first_name.errors|escape}}
                      </div>
                  </div>
              </div>





              <div class='row'>
                  <div class='input-field col s8 offset-s2'>
                      <input type="text" value='{{usern.2}}' name="last_name" id="id_last_name" required maxlength="100" />
                      <label for="id_last_name">Last name:</label>
                      <div class="error">
                        {{form.last_name.errors|escape}}
                      </div>
                  </div>
              </div>





              <div class='row'>
                  <div class='input-field col s8 offset-s2'>
                      <input type="text" value='{{usern.3}}' name="email" id="id_email" required maxlength="100" />
                      <label for="id_email">E mail:</label>
                      <div class="error">
                        {{form.email.errors|escape}}
                      </div>
                  </div>
              </div>


            {%with 'admission_number first_name last_name email' as list%}
            {%for field in form%}
            {%if field.name not in list%}
            <div class='row'>
                <div class='input-field col s8 offset-s2'>

                    {{field}}
                    {{ field.label_tag }}
                    {% if field.errors%}
                    <div class = "error">
                      {{field.errors|striptags}}
                    </div>
                    {% endif %}
                </div>
            </div>
            {%endif%}
            {%endfor%}
            {%endwith%}





                <div class='row'>
                    <button type="submit" class="col offset-s2 s8 waves-effect waves-light btn green">Register</button>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

mhsite/templates/mhsite/students/studentscorner.html
{% extends 'base.html' %}

{% block body %}

    <div class='container'>
        <div class="card card-panel" style="margin-top:15px; background-color:rgba(0, 0, 0, 0.6)">
            <div class="row">
                <div class="col s12 m12">
                  <div class="card blue-grey darken-1">
                    <div class="card-content white-text">
                      <span class="card-title">Profile</span>
                      <table>
                          <tr>
                              <td>Admission Number:</td><td>{{data.admission_number}}</td>
                          </tr>
                          <tr>
                              <td>First Name:</td><td>{{data.first_name}}</td>
                          </tr>
                          <tr>
                              <td>Last Name:</td><td>{{data.last_name}}</td>
                          </tr>
                          <tr>
                              <td>E mail:</td><td>{{data.email}}</td>
                          </tr>
                          <tr>
                              <td>Room no:</td><td>{{data.room_number}}</td>
                          </tr>
                          <tr>
                              <td>Address:</td><td>{{data.address}}</td>
                          </tr>
                          <tr>
                              <td>Pincode:</td><td>{{data.pincode}}</td>
                          </tr>
                          <tr>
                              <td>Phone No:</td><td>{{data.phone}}</td>
                          </tr>
                          <tr>
                              <td>Date of birth:</td><td>{{data.date_of_birth}}</td>
                          </tr>
                          <tr>
                              <td>Catagory:</td><td>{{data.category}}</td>
                          </tr>
                      </table>
                    </div>
                    <div class="card-action">
                      <a href="/accounts/pwdreset">Reset Password</a>
                      <a href="/students/application">Update Details</a>
                    </div>
                  </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}